<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <VersionPrefix>2.1.0</VersionPrefix>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <RootNamespace>GodotTask.GlobalCancellation</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- IDE0290: Use primary constructor -->
        <NoWarn>IDE0290</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <IsAotCompatible>true</IsAotCompatible>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <PropertyGroup>
        <IsGodotToolsProject>true</IsGodotToolsProject>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>GDTask.GlobalCancellation</Title>
        <Authors>Joy-less, DE-YU</Authors>
        <Description>Adds global cancellations to GDTask.Nuget</Description>
        <PackageProjectUrl>https://github.com/Joy-less/GDTask.Nuget.GlobalCancellation</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/Joy-less/GDTask.Nuget.GlobalCancellation</RepositoryUrl>
        <PackageTags>Godot; GDTask; GodotTask; Task; Async; GlobalCancellation; CancellationToken</PackageTags>
        <PackageIcon>Logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../Logo.png" Pack="true" PackagePath="/" />
        <None Include="../README.md" Pack="true" PackagePath="/" />
        <None Include="../LICENSE.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GDTask" Version="3.0.0" />
        <PackageReference Include="GodotSharp" Version="4.1.0" />
        <PackageReference Include="Godot.SourceGenerators" Version="4.1.0" />
    </ItemGroup>
</Project>
